### ISSUE TITLE
request for community feedback: python API

### ISSUE THREAD

**Issue by pbellec** [brainsprite/brainsprite#93]
I am in the process of establishing the python API for brainsprite, and just pushed an initial design as part of pre-release 0.14.2. I would very much appreciate feedback and advice on this.  

For years, brainsprite has required users to somehow generate the sprites and meta-data themselves, greatly limiting the usability of the library, and sometimes leading to errors. There is now a clean python API to do those tasks, which I adapted from earlier code contributed to nilearn. This early code made it really easy to build an html with a single viewer, and already opened a lot of applications. But the vision for brainsprite has always been to be connected with other interactive objects. like in this [example](https://simexp.github.io/multiscale_dashboard/index.html). So I have refactored the code, trying to keep the syntax clean and compart, but adding flexibility.

You can look at this [tutorial](https://brainsprite.github.io/auto_examples/plot_stat_map.html#sphx-glr-auto-examples-plot-stat-map-py), if you want to see in a real code how that works (you may also want to read the [overview](https://brainsprite.github.io/QUICKSTART.html) of brainsprite before reading the tutorial). I will outline the gist of the API here. In effect, what needs to happen is to generate two code snippets, one in html and the other one in javascript, that get inserted in an html document. What I came up with follows the `__init__` | `fit` | `transform` API common in `sklearn` and `nilearn`. You first init the viewer with whatever parameter you would use in nilearn's `view_img`:
```
from brainsprite import viewer_substitute
bsprite  = viewer_substitute(opacity=0.5)
``` 
Then you `fit` the object, which means you extract the sprites and meta-data for an img (possibly with a background): 
``` 
bsprite.fit(img)
``` 
The model now has attributes like `html_` and `javascript_` which are the code snippets, ready to be inserted in an html document. To implement this operation with the API, you load a template using tempita. The `transform` method applies a substitution to the template. The user can pass a usual tempita substitution pattern in addition (called `namespace`), but the user just needs to specify the tags used for the html, javascript code and the brainsprite.js library, with brainsprite picking the appropriate attributes and applying substitution internally. 
``` 
import tempita 
tmpl = tempita.Template("{{ title }} {{ html }} {{ library}} {{js}}") 
viewer_html = bsprite.transform( javascript='js', html='html', library='library', namespace={ "title": "a title"} )
``` 
the `viewer_html` is a `StatMapView` html document class from nilearn: it inserts itself inside notebooks when called, and can be converted to a string, or dumped in a file. 

I do have a number of open question with this approach: 
 * is that intuitive?
 * is that going to conflict with more advanced usage of tempita? 
 * how will it work to insert multiple viewers (and possibly sync them)? 

I would appreciate any feedback, positive or negative, on this API. I only just made the 0.14.2 pre-release, and it is still easy to adjust this design decision.

**Comment by emdupre** [comment]
Thanks for making this great library, @pbellec, and for putting so much careful thought into its design !

Personally, I find the object -> `.fit` -> `.transform`  method to be somewhat unintuitive in a visualization workflow. I wonder if you couldn't model a structure a little closer to bokeh (or at least how I've used seen it used by @javiergcas in [tedana dynamic reports](https://github.com/ME-ICA/tedana/pull/457/files#diff-ffd82076278e20543fd4fb9e4b0db65e)) where:

- individual visualizations have relatively discrete function calls e.g., `plotting.figure`
- Units can be linked to sync updates across figures

The difference between brainsprite and bokeh (or one of the differences, rather) is that you don't need to add successive layers of interactivity on individual sprites, so it could likely be even simpler to instantiate individual figures.

The benefit of this is that users don't need to worry about `tempita` or any other low-level functionality and could instead think about creating links between viewers and other objects. I also don't know that it would stop advanced users from creating more complex viewers, as they could still access brainsprite's private functions. _And_ if there's enough interest over time, those complex viewers could gain public-facing functionality.

Regardless, thanks again for the work, here, and for the chance to have this discussion !

**Comment by emdupre** [comment]
Also wanted to cc in @62442katieb since she used the older brainsprite API to [create linked viewers](https://github.com/emdupre/tedana/pull/21) at AFNI code convergence !

**Comment by pbellec** [comment]
@emdupre Huge thanks for taking the time to provide feedback. I am going to check out the resources in bokeh and tedana. But if I understand what you suggest, it would look like: 
``` 
brain1 = bsprite(img1, title="an image")
brain2 = bsprite(img2, title="another image")
brain.sync(brain2) # sync brain1 and brain2
``` 
If I go down that path, would you still expect nilearn's HTMLDocument behavior?:
``` 
brain # show brain in a jupyter notebook
brain.save_as_html('brain.html') # dump in an html file
str(brain) # get the html dump 
``` 
And if you wanted to assemble several viewers in the same template, something like:
```
tmlp = tempita.Template("page_template.html")
tmlp.substitute(tag1=str(brain1), tag2=str(brain2)) 
``` 
This is assuming I could bundle the entire viewer inside a single tag, merging html and js into one piece of code. 

> I also don't know that it would stop advanced users from creating more complex viewers, as they could still access brainsprite's private functions. 

I guess my main objective at the moment is to have these private functions made public and well documented. The more advanced viewer use cases will follow. 

> And if there's enough interest over time, those complex viewers could gain public-facing functionality.

Yes, absolutely. That's how I am hoping brainsprite to move forward, being one element in turn-key reporting templates. Whether those templates would be generic and hosted as part of the brainsprite library, or specialized and hosted elsewhere (tedana, nilearn, etc), remains to be seen.  

> wanted to cc in @62442katieb since she used the older brainsprite API to create linked viewers at AFNI code convergence !
@62442katieb your feedback on that experiment would be very valuable.

**Comment by ltetrel** [comment]
To plot a figure using `fit`, you first need to initialize the object `viewer_substitute` (ex `threshold=3` etc..).
What if I want to update these parameters "on the fly" , without instantiating a new `viewer_substitute` object ?
Maybe you could have a setter for each of these parameters, or a global one.
ex: `viewer_substitute.update_params(threshold=4, opacity=2,)`

I am not sure about the memory usage of `viewer_substitute`, but it makes sense to do that if you want to have different parameters on the same data, without storing multiple instances of `viewer_substitute`.

**Comment by pbellec** [comment]
@ltetrel thanks for the feedback. It is a neat idea. The `viewer_substitute` object is fairly large, as it contains the background and overlay sprite. The use case is not clear to me though. What I can think of is a backend server, where the user wants to adjust one of the parameters, e.g. opacity. Is that what you had in mind?

**Comment by ltetrel** [comment]
I think this solution would not need a backend server. But of course an optionnal backend server could be usefull if the user does not have the ressources for `brainsprite :) 
I think this is what `plotly` is doing ?

**Comment by pbellec** [comment]
sorry if I wasn't clear. I am trying to figure out under what circumstances a user would like to update the parameter of a viewer, or have two viewers with different parameters like in your example.

**Comment by ltetrel** [comment]
hmm, if one wants to share his results, but with different parameters but same data? 
For example `threshold` can be used on one plot to hide un-relevant artifacts (a user would increase `threshold`, to emphase particular structures in the brain), and on the other plot show the impact of the noise on the data (he would then decrease the `threshold`, so more pixel information is shown).

**Comment by pbellec** [comment]
@ltetrel thanks for clarifying. I think it would be possible to use regexp to change some of the parameters after the html has been generated (like opacity). This would be much faster than regenerating the viewer.

**Comment by emdupre** [comment]
> But if I understand what you suggest, it would look like:

Yes, that's exactly what I was thinking ! 

> If I go down that path, would you still expect nilearn's HTMLDocument behavior?

Personally, I think it's still feasiable. The trick would be for those instances where you have synced viewers, the `save_as_html` as done for a single object makes less sense. But, that call was never designed to handle multiple objects.

I wonder if you could add in the reporting templates to the `save_as_html` call. Whether that's done through tempita or something slightly higher level is perhaps a different point. Either way, `save_as_html` ( or `open_in_browser`) could either accept a report structure or -- if no structure was passed -- then it would default to implementing the current structure for handling only one HTML object.

**Comment by 62442katieb** [comment]
Thanks for putting this together, @pbellec! Sprites are a great visualization tool and I'm glad to see this API :)

I took a look and it seems intuitive/good to me! And built-in synching capability would be a dream!

Generating sprites is clear & straightforward with `fit`, but I might add a few sentences to the documentation of `viewer_substitute` for users less familiar with html, so that labels for canvas/sprite/sprite_overlay/img_colorMap are used correctly. I suppose this isn't a high priority, as they're all optional parameters, but it could be helpful in the long run. 

While I agree with @emdupre that fit/transform isn't the most intuitive for figure creation, it's intuitive for those familiar with sklearn and nilearn, so I don't have a strong opinion either way.

> Yes, absolutely. That's how I am hoping brainsprite to move forward, being one element in turn-key reporting templates. Whether those templates would be generic and hosted as part of the brainsprite library, or specialized and hosted elsewhere (tedana, nilearn, etc), remains to be seen.

I think there's room for (and value in) both generic, brainsprite library tempaltes and specialized, tool-specific templates. What a great idea!

> I wonder if you could add in the reporting templates to the `save_as_html` call. Whether that's done through tempita or something slightly higher level is perhaps a different point. Either way, `save_as_html` ( or `open_in_browser`) could either accept a report structure or -- if no structure was passed -- then it would default to implementing the current structure for handling only one HTML object.

Adding reporting templates to the `save_as_html` call would be a nice way to build on existing functionality (i.e., nilearn's HTMLDocument behavior) and

**Comment by pbellec** [comment]
thanks a lot for sharing your thoughts @62442katieb, this is starting to take shape. 

First, following @emdupre and @62442katieb's idea, brainsprite would primarily be a library of generic visualization, e.g.: a basic 3D viewer, a 4D data viewer, a registration viewe (with opacity-transition between two volumes), a connectome viewer (linking connections with corresponding brain parcels), a seed-based viewer where clicking on a parcel selects seed based maps (like [this](https://simexp.github.io/dashboard_rmap_cobre/rmap.html), etc. This would use the nilearn HTMLDocument class, and pure python (no js or html involved for users).

The code of these viewers would also act as a gallery of code examples. The rest of the API would only be outlined in the dev docs, along with the javascript API. The basic mechanism would go like: 
``` 
brain = brain_data(img)
tpl = tempita.Template("{{ html }} {{ js }}")
tpl.substitute(html=brain.html(), js=brain.js())
``` 
It would be possible to update the viewer parameters after initialization, a la bokeh, and following @ltetrel suggestion:
 ``` 
brain = brain_data(img)
brain.js() # all default parameters
brain.opacity = 1 
brain.js() # now updated js with opacity at 1 
``` 
In terms of linking, it would go as:
``` 
brain1 = brain_data(img1) 
brain2 = brain_data(img2) 
brain2.link(brain1)
```  
Re the tags @62442katieb I think I am going to go with a single name for the viewer, and use standard tags `<name>_bg`, `<name>_overlay` etc. 

I think this will lead to clean code, even for fairly complex viewers. Thanks a lot again @emdupre @ltetrel and @62442katieb  for your feedback, I am going to try and implement that.

**Comment by tyarkoni** [comment]
Hi all,

Sorry for chiming in late (I wasn't logged into mattermost and only just saw a message from @pbellec).

My only suggestion, which is maybe aspirational rather than directly relevant here (see below), would be to maybe consider an API general enough to handle other viewers in a standardized way. @pbellec, it's unclear to me when you say brainsprite would be "a library of generic visualization" if you mean brainsprite would be an abstraction layer and interface that can wrap arbitrary viewing methods, or if the sprite-based approach is integral. If the latter, I would suggest thinking about ways that the brainsprite-specific elements (e.g., the sprite generation and  serving) can be decoupled from the interface.

My own preference would be for something fairly object-oriented. Consider the following example (this is stream of thought, so not intended as a serious proposal, just a sketch):

```python
from generic_plotting_lib import BrainImageManager
from brainsprite import SpriteViewer
from other_pkg import OrthSliceViewer

manager = BrainImageManager()
manager.add_underlay('anatomical.nii.gz')
manager.add_layer('my_image.nii.gz', id=1, label='awesome results')
manager.add_layer('my_other_image.nii.gz', id=2, label='ignore this', sync=[1])

view1 = SpriteViewer(element='#view1', type_='2d')
view2 = OrthSliceViewer(element='#view2', default_color_map='Jet', axes=['X', 'Z'])
manager.register_viewers([view1, view2], sync=True)

html = manager.render(html_template, js_template)
html.save('index.html')
```

I'm sure the above doesn't work for many reasons, and there would probably be quite a bit of work involved in the Python-to-JS transpilation step (since all the syncing etc. would have to work in JS; it's not like there would be callbacks to Python). Ideally something like the above would first exist natively in JS, and then a Python API could be written for it. But regardless, the key element is the separate of the data model (the image layers, cursor position, syncing between viewers, etc.) from the plotting. It would be really nice to be able to say "look, insert a brainspite viewer with these settings on the page at this element, and then add a papaya viewer over here", and have everything nicely sync up via a common data model.

I guess this probably doesn't matter much right now in the sense that whatever you come up with here, it will probably be fairly easy to wrap it in a `Viewer` class of the kind sketched above in the event such a thing ever exists. But to the degree it's worth anticipating what a general-purpose Python neuroimaging visualization API might look like, it may be worth thinking about a bit. (As most of you probably know, there have been many abortive attempts to build a common interface of this sort in JS, dating back to the Berlin OHBM hackathon, but it never seems to take off—probably because it needs to be someone's full-time baby for a few weeks/months to really get going.)

**Comment by pbellec** [comment]
Huge thanks @tyarkoni for sharing your thoughts. 
Lots to unpack here and I am likely going to need a bit of time to fully digest.

> it's unclear to me when you say brainsprite would be "a library of generic visualization" 

What I mean by that is to have some examples which can be modified to serve as a basis for more complex use case. At this stage I want to (finally) have a flexible and clean python API for brainsprite.js. But sometimes thinking more generally brings simplicity rather than complexity, so I am in for the ride and, who knows, the brainsprite interface may serve as a stepping stone to the long-anticipated viewer-agnostic interface.

 > the key element is the separate of the data model (the image layers, cursor position, syncing between viewers, etc.) from the plotting.

the data model being handled by:
```python 
manager = BrainImageManager()
```
I am not 100% following how this would work, but there are things I really like about the idea. First, I can centralize the generation of sprites for the page, so if some viewers share some images there is no duplication. I anticipate that it will often be the case for the underlay. Second, it may be a bit easier to handle syncing of all viewers in one pass, and check that tag names do not conflict, rather than sync them iteratively as was previously proposed. Finally, I also really like the idea of separating the sprite/meta data of each nifti volume from the parameters of the javascript library. This will require some minor changes in the js api actually, but will be an improvement both for the js and py APIs. 

```python 
view1 = SpriteViewer(element='#view1', type_='2d') 
manager.add_layer('my_image.nii.gz', id=1, label='awesome results')
```
I think I would rather have `tag` than `element` and `label`, because those will correspond to tags in the html and js templates, as well as html element IDs and js variable names 
```python
html = manager.render(html_template, js_template)
html.save('index.html')
``` 
I guess there could be a tempita based renderer built-in. I like the idea of separating the html and js templates, this will simplify the tags. I would also like to generate js and html snippets, so it can be used with other templating mechanisms easily. 

Other quick comments. Re `add_underlay` and `add_layer`, those are images which may be used as underlay or layer by different viewers. So I would go for a generic `add_img`. Re `sync` in the call to `add_layer`, again what needs to be synced are the viewers, rather than the images. Finally, adding viewers could be done at the level of the manager itself.
So here is an updated proposal: 
```python
from brainsprite import SpriteManager

manager = SpriteManager()
manager.add_img('my_anatomical.nii.gz', tag='anat')
manager.add_img('ica1.nii.gz', tag='ica1') 
manager.add_img('ica2.nii.gz', tag='ica2')

manager.add_viewer('viewer1', opacity=0.5, title='awesome results', bg_img='anat', 
    layer_img='ica1', layer_colormap='Jet')
manager.add_viewer('viewer2', opacity=0, title='ignore this', bg_img='anat', 
    layer_img='ica2')

manager.sync_viewers([view1, view2])

# get a nilearn HTMLDocument, which supports insertion in notebook, dumping in html etc
doc = manager.render(html_template, js_template) 

# get the html viewer snippets
# will access through html.viewer1, html.viewer2 etc 
html = manager.html() 
# get the javascript viewer snippets
# will access through js.viewer1, js.viewer2 etc 
js = manager.js() # get the javascript snippet # will access
``` 
Final note, if I understood correctly what your intent is, then add_viewer would get an additional parameter `engine`, which would correspond to `OrthSliceViewer(element='#view2', colormap='Jet', axes=['X', 'Z'])`, so I basically only extend your idea for the manager here. I need to think more how the engine function would work, abstracting away the brainsprite specifics. 

Final note number 2, maybe one of the reasons the generic API has not materialized yet is that it was framed as a javascript project. I have touched a bit to javascript, but I suck at it and I am struggling to maintain the very small code base of brainsprite.js already. Maybe having a python based API is actually the way to get this project off the ground.
```

**Comment by tyarkoni** [comment]
@pbellec I think the main difference between our takes is that I'm considering a scenario where a user wants to combine brainsprite with one or more viewers/applications that don't use sprites at all. So, in my conception, the `BrainImageManager` class (maybe `Dashboard` is a better name) wouldn't directly do any sprite generation, because that's something that's specific to brainsprite. The `Dashboard` class would only store data/metadata/state that's completely viewer-agnostic (i.e., which images are loaded and available; how they're ordered; the current cursor coordinates; etc.).

That said, I agree that maintain a separation between loading and rendering *within* brainsprite also makes sense. That could be done in various ways, e.g., by having a separate `Loader` hierarchy. Maybe something like this:

```python
loader = BrainSpriteLoader()
# note reference to the loader, so that the viewer's render() can call it as needed
viewer = SpriteViewer(tag='mytarget', type_='2d', loader=loader)
layer_ui = LayerListUI()
dashboard = Dashboard()

# Register the brainsprite loader and viewer
dashboard.add_loader(loader)
dashboard.add_viewer(viewer, opacity=0.5, title='awesome results',
                     bg_img='anat',  layer_img='ica1', layer_colormap='Jet')

# Register a UI widget that manages layers nicely
dashboard.add_interface(layer_ui)

# Now we can add images...
dashboard.add_img('my_anatomical.nii.gz', tag='anat')
dashboard.add_img('ica1.nii.gz', tag='ica1') 
dashboard.add_img('ica2.nii.gz', tag='ica2')

# Calls .load() on any internally stored loaders, e.g., for sprite generation;
# could also be done implicitly by render().
dashboard.setup()
# Calls .render() on any internally stored viewers/interfaces, and then injects
# their outputs into the global templates.
doc = dashboard.render(html_template, js_template)
```

The key here is that all brainsprite-specific loading is handled inside the `BrainSpriteLoader` class, and since the `SpriteViewer` has access to both the `Dashboard` and `BrainSpriteLoader`, it can get whatever data it needs to. But the `Dashboard` knows nothing about sprites, and the extent of its involvement is to call `BrainSpriteLoader.load()` before rendering.

To give a sense of why the viewer-agnosticism is important, I've thrown in a `LayerListUI` component, which could be some nicely styled widget that allows you to select which image is currently visible, adjust colors and thresholds, etc. Since the widget would only be updating the data model inside the `Dashboard`, and any change would trigger a re-render, you get free interoperability/syncing between potentially very different viewers, even if they each depend on their own support layers (e.g., the `SpriteViewer` needing to access sprites generated by the `BrainSpriteLoader`).

> Final note number 2, maybe one of the reasons the generic API has not materialized yet is that it was framed as a javascript project. I have touched a bit to javascript, but I suck at it and I am struggling to maintain the very small code base of brainsprite.js already. Maybe having a python based API is actually the way to get this project off the ground.

I agree that if we could do this strictly in Python, this would be far more straightforward. But having a Python API is by itself not terribly useful (except maybe in providing some more motivation), because we'd still need a JS API to get the kind of interoperability envisioned above (and without that, there's little reason to have a viewer-independent dashboard layer). I.e., you can't have a layer-selection widget talk to brainsprite unless the common data model is also written as a JS library. And I think it would be a bit ass-backwards to write a Python API in advance of such a library, because the architecture of a convenient/effective JS library should constrain the wrapping Python API, and not the other way around.

Anyway, I'll reiterate that I don't think this should block you on coming up with a sensible brainsprite-specific Python API; I only wanted to bring it up to encourage a structure that might make it easier to wrap whatever you come up with in a more generic layer in the event that one day a generic JS library and (associated Python interface) does exist. :)

**Comment by pbellec** [comment]
hi @tyarkoni huge thanks for the follow up. Last week was the UdeM week at brainhack school and I am only getting a chance to respond now.

I get your point and I think it makes sense to have a dedicated class for loading. It would help structure the code actually. These functionalities are currently provided through these sections of the code https://github.com/brainsprite/brainsprite/blob/master/brainsprite/brainsprite.py#L29-L154 and https://github.com/brainsprite/brainsprite/blob/master/brainsprite/brainsprite.py#L29-L154. It would be beneficial to wrap this code into a separate class with a clean API. Even for viewers that can ingest niftis directly, having such a loader could be useful to convert data from, say, float to uint8 before being served through the web. I don't think the call to `loader` should be visible to users (the `setup` call in your example), but rather triggered through `render()` as you suggested. It is still going to improve the logic of the code, and possibly make it extensible to other viewers. 

re the necessity to develop a "viewer agnostic" javascript library first, it's not clear to me why it wouldn't be possible to develop python code that offers a uniform API and deal under the hood with the idiosyncracies of each viewer's js API, or why it would be easier to achieve that goal starting in js. 

Finally I would like to point out that https://plotly.com/dash/ looks great and I think a next step for brainsprite would be to figure out how to integrate it in dash, so I am going to look into their approach as well.

**Comment by pbellec** [comment]
Two years and a half later :roll_eyes:  

Closing the issue: the design is done. 

I think I am going to give a try at the implementation.
